"""Add event_id and rename earned_at to date_earned in UserEventAchievement

Revision ID: 3ccc345df63a
Revises: c7bc314ebe96
Create Date: 2025-04-03 17:05:37.106357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccc345df63a'
down_revision = 'c7bc314ebe96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event_achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_earned', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_user_event_achievement_event', 'event', ['event_id'], ['id'])
        batch_op.drop_column('earned_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_event_achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earned_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('fk_user_event_achievement_event', type_='foreignkey')
        batch_op.drop_column('date_earned')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
