"""Add max_participants field to Event model

Revision ID: 4346ad4ed0c4
Revises: 3ccc345df63a
Create Date: 2025-04-03 20:25:13.922228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4346ad4ed0c4'
down_revision = '3ccc345df63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_participants', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('max_participants')

    # ### end Alembic commands ###
